import express from 'express';
import cors from 'cors';
import path from 'node:path';
import { generateWithAi, getActiveAiConfig, getAiModels, type AiProvider } from './services/AiModelService';
import { oddsApiService } from './services/OddsApiService';
import { aiPredictionService } from './services/AiPredictionService';
import { footballDataService } from './services/FootballDataService';
import { getUser, login, register, createSession, verifySession } from './services/AuthService';
import { getEffectiveSubscription, requestPayment, listSubscriptions, approveSubscription, banSubscription, deleteSubscription, PAYMENT_NAME, PAYMENT_NUMBER, SUBSCRIPTION_PRICE_UGX } from './services/SubscriptionService';
import { newId, sql } from './lib/db';

const app = express(); app.use(cors()); app.use(express.json());
const ANALYSIS_INTERVAL_MS = 12 * 60 * 60 * 1000;
let manualAnalysisRunning = false;
function authUserId(req: express.Request): string | null { const header = req.headers.authorization || ''; return header.startsWith('Bearer ') ? verifySession(header.slice(7)) : null; }
async function requireAdmin(req: express.Request, res: express.Response): Promise<string | null> { const userId = authUserId(req); if (!userId) { res.status(401).json({ ok: false, error: 'Authentication required' }); return null; } const user = await getUser(userId); const role = String(user?.role || '').toUpperCase(); if (!user || !['ADMIN', 'SUPERADMIN', 'OWNER'].includes(role)) { res.status(403).json({ ok: false, error: 'Administrator access required' }); return null; } return userId; }
export async function startServer(): Promise<void> { const PORT = Number(process.env.PORT || 3001); await new Promise<void>(resolve => app.listen(PORT, '0.0.0.0', () => { console.log(`[API] Server running on port ${PORT}`); resolve(); })); }

app.get('/api/health', async (_req, res) => { try { await sql`SELECT 1 AS ok`; res.json({ ok: true, service: 'SureBet Pro', version: '2.1.0', database: true, databaseProvider: 'Neon PostgreSQL', footballData: footballDataService.isConfigured() }); } catch (error) { console.error('[Health] Neon database check failed:', error); res.status(503).json({ ok: false, service: 'SureBet Pro', version: '2.1.0', database: false, databaseProvider: 'Neon PostgreSQL', footballData: footballDataService.isConfigured() }); } });
app.post('/api/auth/register', async (req, res) => { try { const user = await register(String(req.body?.email || ''), String(req.body?.password || ''), String(req.body?.name || '')); res.status(201).json({ ok: true, user, token: createSession(user) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Registration failed' }); } });
app.post('/api/auth/login', async (req, res) => { try { const user = await login(String(req.body?.email || ''), String(req.body?.password || '')); res.json({ ok: true, user, token: createSession(user) }); } catch (error) { res.status(401).json({ ok: false, error: error instanceof Error ? error.message : 'Login failed' }); } });
app.get('/api/auth/me', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); const user = await getUser(userId); if (!user) return res.status(401).json({ ok: false, error: 'Session is no longer valid' }); try { const subscription = await getEffectiveSubscription(userId); res.json({ ok: true, user, subscription, payment: { amountUgx: SUBSCRIPTION_PRICE_UGX, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load subscription' }); } });

app.get('/api/subscription', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); try { const subscription = await getEffectiveSubscription(userId); res.json({ ok: true, subscription, payment: { amountUgx: SUBSCRIPTION_PRICE_UGX, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load subscription' }); } });
app.post('/api/subscription/request-payment', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); try { const subscription = await requestPayment(userId); console.log(`[Subscription] Payment approval requested by user ${userId}.`); res.status(202).json({ ok: true, subscription, message: 'Payment request sent to the administrator. Your account remains pending until approved.', payment: { amountUgx: SUBSCRIPTION_PRICE_UGX, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Unable to submit payment request' }); } });
app.get('/api/admin/subscriptions', async (req, res) => { if (!(await requireAdmin(req, res))) return; try { const subscriptions = await listSubscriptions(); res.json({ ok: true, subscriptions, payment: { amountUgx: SUBSCRIPTION_PRICE_UGX, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load subscriptions' }); } });
app.post('/api/admin/subscriptions/:id/approve', async (req, res) => { if (!(await requireAdmin(req, res))) return; try { const subscription = await approveSubscription(req.params.id); res.json({ ok: true, subscription }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Approval failed' }); } });
app.post('/api/admin/subscriptions/:id/ban', async (req, res) => { if (!(await requireAdmin(req, res))) return; try { const subscription = await banSubscription(req.params.id); res.json({ ok: true, subscription }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Ban failed' }); } });
app.delete('/api/admin/subscriptions/:id', async (req, res) => { if (!(await requireAdmin(req, res))) return; try { await deleteSubscription(req.params.id); res.json({ ok: true }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Delete failed' }); } });

app.get('/api/opportunities', async (_req, res) => { try { const rows = await sql`SELECT o.id, o.market_key, o.roi, o.profit, o.created_at, json_build_object('home_team', e.home_team, 'away_team', e.away_team, 'commence_time', e.commence_time, 'league_title', e.league_title, 'sport_key', e.sport_key) AS events, COALESCE(json_agg(json_build_object('id', l.id, 'outcome_name', l.outcome_name, 'bookmaker', l.bookmaker, 'price', l.price, 'stake_percentage', l.stake_percentage) ORDER BY l.id) FILTER (WHERE l.id IS NOT NULL), '[]'::json) AS surebet_legs FROM surebet_opportunities o JOIN events e ON e.id = o.event_id LEFT JOIN surebet_legs l ON l.opportunity_id = o.id WHERE o.is_active = true GROUP BY o.id, e.id ORDER BY o.created_at DESC`; res.json({ ok: true, opportunities: rows }); } catch (error) { console.error('[API] Opportunity query failed:', error); res.status(500).json({ ok: false, error: 'Failed to load opportunities', opportunities: [] }); } });
app.post('/api/strategy', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); const opportunityId = String(req.body?.opportunity_id || ''); if (!opportunityId) return res.status(400).json({ ok: false, error: 'opportunity_id is required' }); try { const id = newId(); await sql`INSERT INTO user_strategies (id, user_id, opportunity_id, status) VALUES (${id}, ${userId}, ${opportunityId}, 'pending') ON CONFLICT (user_id, opportunity_id) DO UPDATE SET status = 'pending'`; res.status(201).json({ ok: true }); } catch (error) { console.error('[API] Strategy save failed:', error); res.status(500).json({ ok: false, error: 'Failed to add opportunity to strategy' }); } });
app.get('/api/settings', async (_req, res) => { try { const [sports, markets, bookmakers, settings] = await Promise.all([sql`SELECT key, title, description, active FROM sports ORDER BY title`, sql`SELECT key, title, description, active FROM markets ORDER BY title`, sql`SELECT key, title, active FROM bookmakers ORDER BY title`, sql`SELECT id, min_roi, deep_scan, odds_api_key, api_base_url, api_endpoint_odds, last_run_date, last_run_at, last_run_status FROM system_settings WHERE id = 1`]); res.json({ ok: true, sports, markets, bookmakers, settings: settings[0] || { id: 1, min_roi: 1, deep_scan: true } }); } catch (error) { console.error('[API] Settings query failed:', error); res.status(500).json({ ok: false, error: 'Failed to load settings' }); } });
app.patch('/api/settings', async (req, res) => { try { const body = req.body || {}; if (typeof body.min_roi === 'number' || typeof body.deep_scan === 'boolean') await sql`UPDATE system_settings SET min_roi = COALESCE(${typeof body.min_roi === 'number' ? body.min_roi : null}, min_roi), deep_scan = COALESCE(${typeof body.deep_scan === 'boolean' ? body.deep_scan : null}, deep_scan) WHERE id = 1`; if (typeof body.odds_api_key === 'string' || typeof body.api_base_url === 'string' || typeof body.api_endpoint_odds === 'string') await sql`UPDATE system_settings SET odds_api_key = COALESCE(${typeof body.odds_api_key === 'string' ? body.odds_api_key : null}, odds_api_key), api_base_url = COALESCE(${typeof body.api_base_url === 'string' ? body.api_base_url : null}, api_base_url), api_endpoint_odds = COALESCE(${typeof body.api_endpoint_odds === 'string' ? body.api_endpoint_odds : null}, api_endpoint_odds) WHERE id = 1`; if (body.sportKey && typeof body.active === 'boolean') await sql`UPDATE sports SET active = ${body.active} WHERE key = ${body.sportKey}`; if (body.marketKey && typeof body.active === 'boolean') await sql`UPDATE markets SET active = ${body.active} WHERE key = ${body.marketKey}`; if (body.bookmakerKey && typeof body.active === 'boolean') await sql`UPDATE bookmakers SET active = ${body.active} WHERE key = ${body.bookmakerKey}`; res.json({ ok: true }); } catch (error) { console.error('[API] Settings update failed:', error); res.status(500).json({ ok: false, error: 'Failed to update settings' }); } });
app.get('/api/alerts', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ error: 'Authentication required' }); try { const rows = await sql`SELECT id, min_roi, sport_key, created_at FROM user_alerts WHERE user_id = ${userId} ORDER BY created_at DESC`; res.json({ ok: true, alerts: rows }); } catch { res.status(500).json({ error: 'Failed to load alerts' }); } });
app.post('/api/alerts', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ error: 'Authentication required' }); try { const id = newId(); await sql`INSERT INTO user_alerts (id, user_id, min_roi, sport_key) VALUES (${id}, ${userId}, ${Number(req.body?.min_roi ?? 3)}, ${String(req.body?.sport_key ?? 'soccer')})`; res.status(201).json({ ok: true }); } catch { res.status(500).json({ error: 'Failed to create alert' }); } });
app.delete('/api/alerts/:id', async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ error: 'Authentication required' }); try { await sql`DELETE FROM user_alerts WHERE id = ${req.params.id} AND user_id = ${userId}`; res.json({ ok: true }); } catch { res.status(500).json({ error: 'Failed to delete alert' }); } });
app.get('/api/reports', async (_req, res) => { try { const stats = await sql`SELECT COUNT(*)::int AS total, COALESCE(AVG(roi), 0)::float AS avg_roi, COALESCE(SUM(profit), 0)::float AS total_profit FROM surebet_opportunities WHERE is_active = true`; const daily = await sql`SELECT DATE(created_at) AS date, COUNT(*)::int AS opportunities, COALESCE(AVG(roi), 0)::float AS roi FROM surebet_opportunities WHERE created_at >= NOW() - INTERVAL '30 days' GROUP BY DATE(created_at) ORDER BY date`; res.json({ ok: true, stats: stats[0] || { total: 0, avg_roi: 0, total_profit: 0 }, daily }); } catch (error) { console.error('[API] Report query failed:', error); res.status(500).json({ error: 'Failed to load reports' }); } });

app.get('/api/football/live', async (_req, res) => { try { const matches = await footballDataService.getLiveMatches(); const normalized = matches.map(match => ({ id: match.id, league: match.league, homeTeam: match.homeTeam, awayTeam: match.awayTeam, homeScore: match.homeScore, awayScore: match.awayScore, status: match.status, startTime: match.kickoff, minute: null })); res.json({ ok: true, updatedAt: new Date().toISOString(), count: normalized.length, matches: normalized }); } catch (error) { const message = error instanceof Error ? error.message : 'Live football feed failed'; console.error('[Football] football-data.org live feed failed:', message); res.status(502).json({ ok: false, error: message, matches: [] }); } });
app.get('/api/football/predictions', async (_req, res) => { try {
  const rows = await sql`SELECT f.id, f.league_name, f.home_team, f.away_team, f.kickoff_at, p.winner, p.advice, p.analysis, p.key_factors, p.confidence, p.home_win, p.draw, p.away_win, p.under_over, p.predicted_home_goals, p.predicted_away_goals, p.ai_provider, p.ai_model FROM football_fixtures f LEFT JOIN football_ai_predictions p ON p.fixture_id = f.id WHERE f.kickoff_at >= NOW() - INTERVAL '2 hours' AND f.kickoff_at <= NOW() + INTERVAL '7 days' ORDER BY f.kickoff_at ASC`;
  const [settings] = await Promise.all([sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`]);
  const lastRunAt = settings?.[0]?.analysis_last_run_at ? new Date(settings[0].analysis_last_run_at).toISOString() : null;
  const predictions = rows.map((row: any) => ({ id: String(row.id), league: row.league_name, homeTeam: row.home_team, awayTeam: row.away_team, startTime: new Date(row.kickoff_at).toISOString(), winner: row.winner || null, advice: row.advice || null, analysis: row.analysis || null, keyFactors: Array.isArray(row.key_factors) ? row.key_factors : [], confidence: row.confidence == null ? null : Number(row.confidence), homeWin: row.home_win == null ? null : Number(row.home_win), draw: row.draw == null ? null : Number(row.draw), awayWin: row.away_win == null ? null : Number(row.away_win), underOver: row.under_over || null, predictedHomeGoals: row.predicted_home_goals == null ? null : Number(row.predicted_home_goals), predictedAwayGoals: row.predicted_away_goals == null ? null : Number(row.predicted_away_goals), aiProvider: row.ai_provider === 'gemini' || row.ai_provider === 'groq' ? row.ai_provider : null, aiModel: row.ai_model || null }));
  res.json({ ok: true, updatedAt: lastRunAt || new Date().toISOString(), count: predictions.length, predictions, analysisLastRunAt: lastRunAt, analysisLastRunStatus: settings?.[0]?.analysis_last_run_status ?? null, running: manualAnalysisRunning });
} catch (error) { const message = error instanceof Error ? error.message : 'Match predictions failed'; console.error('[Football] AI prediction feed failed:', message); res.status(502).json({ ok: false, error: message, predictions: [] }); } });
app.get('/api/football/analysis-status', async (_req, res) => { try { const [rows] = await Promise.all([sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`]); res.json({ ok: true, running: manualAnalysisRunning, lastRunAt: rows?.[0]?.analysis_last_run_at ? new Date(rows[0].analysis_last_run_at).toISOString() : null, status: rows?.[0]?.analysis_last_run_status ?? null }); } catch (error) { res.status(503).json({ ok: false, running: manualAnalysisRunning, status: 'unknown' }); } });
app.post('/api/football/analyze-now', async (_req, res) => { if (manualAnalysisRunning) return res.status(409).json({ ok: false, running: true, error: 'Football analysis is already running.' });
  manualAnalysisRunning = true;
  await sql`UPDATE system_settings SET analysis_last_run_status = 'running' WHERE id = 1`;
  console.log('[AI] Manual football analysis requested from dashboard. Starting background analysis for all fetched games in small AI batches.');
  void (async () => {
    try {
      const predictions = await aiPredictionService.runAutomaticAnalysis(Number.MAX_SAFE_INTEGER);
      const completedAt = new Date();
      await sql`UPDATE system_settings SET analysis_last_run_at = ${completedAt.toISOString()}, analysis_last_run_status = ${predictions.length ? 'success' : 'no_fixtures'} WHERE id = 1`;
      console.log(`[AI] Background manual analysis finished: ${predictions.length} predictions stored across all fetched games.`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Manual football analysis failed';
      console.error('[AI] Background manual analysis failed:', message);
      await sql`UPDATE system_settings SET analysis_last_run_at = NOW(), analysis_last_run_status = 'failed' WHERE id = 1`;
    } finally { manualAnalysisRunning = false; }
  })();
  res.status(202).json({ ok: true, running: true, queued: true, batchSize: 6, target: 'all fetched games', message: 'Football analysis started. Games and completed predictions will appear progressively.' });
});
app.get('/api/ai/models', (_req, res) => res.json({ active: getActiveAiConfig(), models: getAiModels() }));
app.post('/api/ai/generate', async (req, res) => { try { const body = req.body as { provider?: AiProvider; prompt?: string; system?: string; temperature?: number; maxTokens?: number }; if (!body.prompt || typeof body.prompt !== 'string') return res.status(400).json({ error: 'prompt is required' }); if (body.provider && body.provider !== 'gemini' && body.provider !== 'groq') return res.status(400).json({ error: 'provider must be gemini or groq' }); const content = await generateWithAi(body); res.json({ ok: true, provider: body.provider || getActiveAiConfig().provider, content }); } catch (error) { const message = error instanceof Error ? error.message : 'AI generation failed'; console.error('[AI] Generation failed:', message); res.status(502).json({ error: message }); } });
app.get('/api/scheduler', async (_req, res) => { try { const rows = await sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`; const data = rows[0]; const lastRunAt = data?.analysis_last_run_at ? new Date(data.analysis_last_run_at).toISOString() : null; res.json({ enabled: true, intervalHours: 12, liveRefreshMinutes: 2, timezone: 'Africa/Kampala', lastRunDate: lastRunAt ? lastRunAt.slice(0, 10) : null, lastRunAt, lastRunStatus: data?.analysis_last_run_status ?? null, nextRunAt: lastRunAt ? new Date(new Date(lastRunAt).getTime() + ANALYSIS_INTERVAL_MS).toISOString() : null }); } catch { res.status(503).json({ enabled: true, intervalHours: 12, liveRefreshMinutes: 2, timezone: 'Africa/Kampala', lastRunDate: null, lastRunAt: null, lastRunStatus: null, nextRunAt: null }); } });

const frontendDist = path.resolve(process.cwd(), 'dist');
app.use(express.static(frontendDist));
app.get('*', (_req, res) => res.sendFile(path.join(frontendDist, 'index.html')));
