import express from 'express';
import cors from 'cors';
import fs from 'node:fs';
import path from 'node:path';
import { getAiModels } from './services/AiModelService';
import { aiPredictionService } from './services/AiPredictionService';
import { footballDataService } from './services/FootballDataService';
import { getUser, login, register, createSession, revokeSession, verifySession } from './services/AuthService';
import { getEffectiveSubscription, requestPayment, listSubscriptions, approveSubscription, banSubscription, deleteSubscription, PAYMENT_NAME, PAYMENT_NUMBER, PAYMENT_PLANS } from './services/SubscriptionService';
import { scannerScheduler } from './engine/ScannerScheduler';
import { sql } from './lib/db';
const app = express(); app.use(cors()); app.use(express.json({ limit: '1mb' })); const API_BASE = '/api'; let manualAnalysisRunning = false;
function authUserId(req: express.Request): string | null { const header = req.headers.authorization || ''; return header.startsWith('Bearer ') ? verifySession(header.slice(7)) : null; }
function hasAdminRole(role: unknown): boolean { const normalizedRole = String(role ?? '').trim().toUpperCase(); return ['ADMIN', 'SUPERADMIN', 'OWNER', 'ADMINISTRATOR'].includes(normalizedRole); }
async function requireAdmin(req: express.Request, res: express.Response): Promise<string | null> { const userId = authUserId(req); if (!userId) { res.status(401).json({ ok: false, error: 'Authentication required' }); return null; } const user = await getUser(userId); if (!user || !hasAdminRole(user.role)) { res.status(403).json({ ok: false, error: 'Administrator access required' }); return null; } return userId; }
app.get(`${API_BASE}/health`, async (_req, res) => { try { await sql`SELECT 1`; const scheduler = scannerScheduler.getStatus(); const settings = await sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`; res.json({ ok: true, service: 'FootballAI', version: '3.0.0', database: true, databaseProvider: 'Neon PostgreSQL', footballData: footballDataService.isConfigured(), scheduler, analysisLastRunAt: settings?.[0]?.analysis_last_run_at || null, analysisLastRunStatus: settings?.[0]?.analysis_last_run_status || null }); } catch (error) { res.status(503).json({ ok: false, service: 'FootballAI', database: false, error: error instanceof Error ? error.message : 'Health check failed' }); } });
app.get(`${API_BASE}/ai/models`, (_req, res) => res.json({ ok: true, active: getAiModels().find(model => model.configured) || getAiModels()[0], models: getAiModels() }));
app.get(`${API_BASE}/scheduler`, async (_req, res) => { try { const settings = await sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`; const status = scannerScheduler.getStatus(); res.json({ enabled: status.running, intervalHours: 12, timezone: process.env.TZ || 'Africa/Kampala', lastRunAt: settings?.[0]?.analysis_last_run_at || status.lastCycleFinishedAt, lastRunStatus: settings?.[0]?.analysis_last_run_status || status.lastCycleStatus, nextRunAt: status.nextRunAt, running: manualAnalysisRunning }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Scheduler status failed' }); } });
app.post(`${API_BASE}/auth/register`, async (req, res) => { try { const user = await register(String(req.body?.email || ''), String(req.body?.password || ''), String(req.body?.name || '')); res.status(201).json({ ok: true, user, token: createSession(user) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Registration failed' }); } });
app.post(`${API_BASE}/auth/login`, async (req, res) => { try { const user = await login(String(req.body?.email || ''), String(req.body?.password || '')); res.json({ ok: true, user, token: createSession(user) }); } catch (error) { res.status(401).json({ ok: false, error: error instanceof Error ? error.message : 'Login failed' }); } });
app.post(`${API_BASE}/auth/logout`, (req, res) => { const header = req.headers.authorization || ''; if (header.startsWith('Bearer ')) revokeSession(header.slice(7)); res.json({ ok: true }); });
app.get(`${API_BASE}/auth/me`, async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); const user = await getUser(userId); if (!user) return res.status(401).json({ ok: false, error: 'Session is no longer valid' }); try { const subscription = await getEffectiveSubscription(userId); res.json({ ok: true, user, subscription, payment: { plans: PAYMENT_PLANS, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load account' }); } });
app.get(`${API_BASE}/subscription`, async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); try { res.json({ ok: true, subscription: await getEffectiveSubscription(userId), payment: { plans: PAYMENT_PLANS, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load subscription' }); } });
app.post(`${API_BASE}/subscription/request-payment`, async (req, res) => { const userId = authUserId(req); if (!userId) return res.status(401).json({ ok: false, error: 'Authentication required' }); try { const subscription = await requestPayment(userId, String(req.body?.plan || 'monthly').toLowerCase()); res.status(202).json({ ok: true, subscription, message: `${PAYMENT_PLANS[subscription.plan].name} payment request sent to the administrator.`, payment: { plans: PAYMENT_PLANS, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Unable to submit payment request' }); } });
app.get(`${API_BASE}/admin/subscriptions`, async (req, res) => { if (!(await requireAdmin(req, res))) return; try { res.json({ ok: true, subscriptions: await listSubscriptions(), payment: { plans: PAYMENT_PLANS, number: PAYMENT_NUMBER, name: PAYMENT_NAME } }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load subscription requests' }); } });
app.post(`${API_BASE}/admin/subscriptions/:id/approve`, async (req, res) => { if (!(await requireAdmin(req, res))) return; try { res.json({ ok: true, subscription: await approveSubscription(req.params.id) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Approval failed' }); } });
app.post(`${API_BASE}/admin/subscriptions/:id/ban`, async (req, res) => { if (!(await requireAdmin(req, res))) return; try { res.json({ ok: true, subscription: await banSubscription(req.params.id) }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Ban failed' }); } });
app.delete(`${API_BASE}/admin/subscriptions/:id`, async (req, res) => { if (!(await requireAdmin(req, res))) return; try { await deleteSubscription(req.params.id); res.json({ ok: true }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Delete failed' }); } });
app.get(`${API_BASE}/football/live`, async (_req, res) => { try { const matches = await footballDataService.getLiveMatches(); res.json({ ok: true, updatedAt: new Date().toISOString(), count: matches.length, matches: matches.map(match => ({ id: match.id, league: match.league, homeTeam: match.homeTeam, awayTeam: match.awayTeam, homeCrest: match.homeCrest, awayCrest: match.awayCrest, homeScore: match.homeScore, awayScore: match.awayScore, status: match.status, startTime: match.kickoff })) }); } catch (error) { res.status(502).json({ ok: false, error: error instanceof Error ? error.message : 'Live football feed failed', matches: [] }); } });
app.get(`${API_BASE}/football/predictions`, async (_req, res) => { try { const rows = await sql`SELECT f.id, f.league_name, f.home_team, f.away_team, f.kickoff_at, f.status, f.raw_data, p.winner, p.advice, p.analysis, p.key_factors, p.confidence, p.home_win, p.draw, p.away_win, p.under_over, p.predicted_home_goals, p.predicted_away_goals, p.ai_provider, p.ai_model FROM football_fixtures f LEFT JOIN football_ai_predictions p ON p.fixture_id = f.id WHERE f.kickoff_at >= NOW() - INTERVAL '2 hours' AND f.kickoff_at <= NOW() + INTERVAL '7 days' ORDER BY f.kickoff_at ASC`; const settings = await sql`SELECT analysis_last_run_at, analysis_last_run_status FROM system_settings WHERE id = 1`; const predictions = rows.map((row: any) => ({ id: String(row.id), league: row.league_name || 'Football', homeTeam: row.home_team, awayTeam: row.away_team, homeCrest: row.raw_data?.homeTeam?.crest || null, awayCrest: row.raw_data?.awayTeam?.crest || null, startTime: new Date(row.kickoff_at).toISOString(), status: row.status, winner: row.winner || null, advice: row.advice || null, analysis: row.analysis || null, keyFactors: Array.isArray(row.key_factors) ? row.key_factors : [], confidence: row.confidence == null ? null : Number(row.confidence), homeWin: row.home_win == null ? null : Number(row.home_win), draw: row.draw == null ? null : Number(row.draw), awayWin: row.away_win == null ? null : Number(row.away_win), underOver: row.under_over || null, predictedHomeGoals: row.predicted_home_goals == null ? null : Number(row.predicted_home_goals), predictedAwayGoals: row.predicted_away_goals == null ? null : Number(row.predicted_away_goals), aiProvider: row.ai_provider === 'gemini' || row.ai_provider === 'groq' ? row.ai_provider : null, aiModel: row.ai_model || null })); const lastRunAt = settings?.[0]?.analysis_last_run_at ? new Date(settings[0].analysis_last_run_at).toISOString() : null; res.json({ ok: true, updatedAt: lastRunAt || new Date().toISOString(), count: predictions.length, predictions, analysisLastRunAt: lastRunAt, analysisLastRunStatus: settings?.[0]?.analysis_last_run_status || null, scheduler: scannerScheduler.getStatus(), running: manualAnalysisRunning }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load predictions' }); } });
app.get(`${API_BASE}/football/history`, async (req, res) => { try { const limit = Math.min(Math.max(Number(req.query.limit || 200), 1), 500); const rows = await sql`SELECT f.id, f.league_name, f.home_team, f.away_team, f.kickoff_at, f.home_score, f.away_score, f.status, f.raw_data, p.winner, p.advice, p.analysis, p.key_factors, p.confidence, p.predicted_home_goals, p.predicted_away_goals, p.ai_provider, p.ai_model FROM football_fixtures f JOIN football_ai_predictions p ON p.fixture_id = f.id WHERE f.status IN ('FINISHED','AWAITING_PENALTIES','FINISHED_AET','FINISHED_PEN','FT','AET','PEN') AND f.home_score IS NOT NULL AND f.away_score IS NOT NULL ORDER BY f.kickoff_at DESC LIMIT ${limit}`; const history = rows.map((row: any) => { const actualWinner = Number(row.home_score) > Number(row.away_score) ? row.home_team : Number(row.away_score) > Number(row.home_score) ? row.away_team : 'Draw'; const predictionCorrect = row.winner ? String(row.winner) === actualWinner : null; const scoreCorrect = row.predicted_home_goals != null && row.predicted_away_goals != null ? Number(row.predicted_home_goals) === Number(row.home_score) && Number(row.predicted_away_goals) === Number(row.away_score) : null; const kickoffAt = new Date(row.kickoff_at).toISOString(); return { id: String(row.id), league: row.league_name || 'Football', homeTeam: row.home_team, awayTeam: row.away_team, kickoffAt, kickoff: kickoffAt, status: row.status, predictedWinner: row.winner || null, actualWinner, actualResult: actualWinner, predictionCorrect, predictedHomeGoals: row.predicted_home_goals == null ? null : Number(row.predicted_home_goals), predictedAwayGoals: row.predicted_away_goals == null ? null : Number(row.predicted_away_goals), actualHomeGoals: Number(row.home_score), actualAwayGoals: Number(row.away_score), scoreCorrect, confidence: row.confidence == null ? null : Number(row.confidence), analysis: row.analysis || row.advice || null, keyFactors: Array.isArray(row.key_factors) ? row.key_factors : [], aiProvider: row.ai_provider || null, aiModel: row.ai_model || null, homeCrest: row.raw_data?.homeTeam?.crest || null, awayCrest: row.raw_data?.awayTeam?.crest || null }; }); res.json({ ok: true, count: history.length, history }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Failed to load prediction history', history: [] }); } });
app.post(`${API_BASE}/football/analyze-now`, async (_req, res) => { if (manualAnalysisRunning) return res.status(409).json({ ok: false, error: 'Analysis is already running.' }); manualAnalysisRunning = true; try { const predictions = await aiPredictionService.runAutomaticAnalysis(Number.MAX_SAFE_INTEGER); await sql`UPDATE system_settings SET analysis_last_run_at = NOW(), analysis_last_run_status = ${predictions.length ? 'success' : 'no_fixtures'} WHERE id = 1`; res.json({ ok: true, count: predictions.length, predictions }); } catch (error) { await sql`UPDATE system_settings SET analysis_last_run_at = NOW(), analysis_last_run_status = 'error' WHERE id = 1`; res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Manual analysis failed' }); } finally { manualAnalysisRunning = false; } });
app.get(`${API_BASE}/admin/health`, async (req, res) => { if (!(await requireAdmin(req, res))) return; try { const [fixtureCount, predictionCount] = await Promise.all([sql`SELECT COUNT(*)::int AS count FROM football_fixtures WHERE kickoff_at >= NOW() - INTERVAL '2 hours' AND kickoff_at <= NOW() + INTERVAL '7 days'`, sql`SELECT COUNT(*)::int AS count FROM football_ai_predictions p JOIN football_fixtures f ON f.id = p.fixture_id WHERE f.kickoff_at >= NOW() - INTERVAL '2 hours' AND f.kickoff_at <= NOW() + INTERVAL '7 days'`]); res.json({ ok: true, database: true, footballData: footballDataService.isConfigured(), upcomingFixtures: Number(fixtureCount[0]?.count || 0), upcomingPredictions: Number(predictionCount[0]?.count || 0), scheduler: scannerScheduler.getStatus() }); } catch (error) { res.status(500).json({ ok: false, error: error instanceof Error ? error.message : 'Admin health check failed' }); } });
const distPath = path.resolve(process.cwd(), 'dist'); if (fs.existsSync(distPath)) { app.use(express.static(distPath)); app.get('*', (_req, res) => res.sendFile(path.join(distPath, 'index.html'))); }
export async function startServer(): Promise<void> { const PORT = Number(process.env.PORT || 3001); await new Promise<void>(resolve => app.listen(PORT, '0.0.0.0', () => { console.log(`[API] FootballAI server running on port ${PORT}`); resolve(); })); }