import React, { useEffect, useState } from 'react';
import { Bell, Plus, Trash2, Loader2 } from 'lucide-react';
import { getAuthToken, useAuth } from '../contexts/AuthContext';

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const headers = () => ({ Authorization: `Bearer ${getAuthToken() || ''}`, 'Content-Type': 'application/json' });

export function Alerts() {
  const { user } = useAuth(); const [alerts, setAlerts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [newAlert, setNewAlert] = useState({ min_roi: 3, sport_key: 'soccer' });
  const fetchAlerts = async () => { try { const r = await fetch(`${API_BASE_URL}/api/alerts`, { headers: headers() }); const data = await r.json(); if (r.ok) setAlerts(data.alerts || []); } finally { setLoading(false); } };
  useEffect(() => { if (user) fetchAlerts(); }, [user]);
  const addAlert = async () => { setSaving(true); try { const r = await fetch(`${API_BASE_URL}/api/alerts`, { method: 'POST', headers: headers(), body: JSON.stringify(newAlert) }); if (r.ok) await fetchAlerts(); } finally { setSaving(false); } };
  const removeAlert = async (id: string) => { await fetch(`${API_BASE_URL}/api/alerts/${id}`, { method: 'DELETE', headers: headers() }); await fetchAlerts(); };
  if (loading) return <div className="h-full flex items-center justify-center"><Loader2 className="w-10 h-10 animate-spin text-indigo-600" /></div>;
  return <div className="p-6 md:p-10 w-full max-w-5xl mx-auto"><div className="flex items-center gap-4 mb-2"><div className="w-12 h-12 rounded-xl bg-indigo-50 flex items-center justify-center"><Bell className="w-6 h-6 text-indigo-600" /></div><h1 className="text-3xl font-extrabold text-slate-900">Alerts</h1></div><p className="text-slate-500 mb-10">Your alert rules are stored in Neon PostgreSQL.</p><div className="bg-white border border-slate-200 rounded-2xl p-6 mb-8"><h2 className="text-lg font-bold mb-4">Create alert</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><input type="number" min="0" step="0.1" value={newAlert.min_roi} onChange={e => setNewAlert({ ...newAlert, min_roi: Number(e.target.value) })} className="border rounded-xl px-4 py-3" placeholder="Minimum ROI %" /><input value={newAlert.sport_key} onChange={e => setNewAlert({ ...newAlert, sport_key: e.target.value })} className="border rounded-xl px-4 py-3" placeholder="Sport key" /><button onClick={addAlert} disabled={saving} className="bg-indigo-600 text-white rounded-xl font-bold px-4 py-3 flex items-center justify-center gap-2">{saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Plus className="w-5 h-5" />}Add alert</button></div></div><div className="space-y-4">{alerts.length === 0 ? <div className="bg-white border border-slate-200 rounded-2xl p-10 text-center text-slate-500">No alert rules configured.</div> : alerts.map(alert => <div key={alert.id} className="bg-white border border-slate-200 rounded-2xl p-5 flex items-center justify-between"><div><div className="font-bold text-slate-900">{alert.sport_key}</div><div className="text-sm text-slate-500">Notify for ROI of {alert.min_roi}% or higher</div></div><button onClick={() => removeAlert(alert.id)} className="p-2 text-red-600 hover:bg-red-50 rounded-lg" aria-label="Delete alert"><Trash2 className="w-5 h-5" /></button></div>)}</div></div>;
}
