import React, { useEffect, useState } from 'react';
import { BrainCircuit, Loader2, RefreshCw, Target } from 'lucide-react';

interface MatchPrediction {
  id: string;
  league: string;
  homeTeam: string;
  awayTeam: string;
  startTime: string;
  winner: string | null;
  advice: string | null;
  analysis: string | null;
  keyFactors: string[];
  confidence: number | null;
  homeWin: number | null;
  draw: number | null;
  awayWin: number | null;
  underOver: string | null;
  predictedHomeGoals: number | null;
  predictedAwayGoals: number | null;
  aiProvider: 'gemini' | 'groq' | null;
  aiModel: string | null;
}

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');

export function Dashboard() {
  const [predictions, setPredictions] = useState<MatchPrediction[]>([]);
  const [updatedAt, setUpdatedAt] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchPredictions = async (manual = false) => {
    if (manual) setRefreshing(true);
    setError(null);
    try {
      const response = await fetch(`${API_BASE_URL}/api/football/predictions`);
      if (!response.ok) throw new Error(`Prediction feed returned ${response.status}`);
      const payload = await response.json();
      setPredictions(Array.isArray(payload.predictions) ? payload.predictions : []);
      setUpdatedAt(payload.updatedAt || new Date().toISOString());
    } catch (err) {
      console.error('Error fetching AI match predictions:', err);
      setError('The AI prediction service is temporarily unavailable.');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchPredictions();
    const timer = window.setInterval(() => fetchPredictions(), 30 * 60_000);
    return () => window.clearInterval(timer);
  }, []);

  const formatProbability = (value: number | null) => value === null ? '—' : `${value.toFixed(0)}%`;
  const formatProvider = (provider: MatchPrediction['aiProvider']) => provider === 'gemini' ? 'Gemini' : provider === 'groq' ? 'Groq' : 'AI';

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white p-6 md:p-10">
      <div className="w-full max-w-7xl mx-auto">
        <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-11 h-11 rounded-2xl bg-[#39FF14]/10 border border-[#39FF14]/20 flex items-center justify-center">
                <BrainCircuit className="w-6 h-6 text-[#39FF14]" />
              </div>
              <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight">AI Football Analysis</h1>
            </div>
            <p className="text-[#8b8d93] text-sm md:text-base max-w-2xl">
              AI analyzes upcoming football fixtures and presents the predicted outcome, probabilities, expected score, confidence, and the reasoning behind each prediction.
            </p>
          </div>
          <button
            type="button"
            onClick={() => fetchPredictions(true)}
            disabled={refreshing}
            className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#2c2e33] bg-[#161618] px-4 py-2.5 text-sm font-semibold hover:bg-[#1d1d20] transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
            Refresh analysis
          </button>
        </header>

        <section className="rounded-2xl border border-[#2c2e33] bg-[#111113] overflow-hidden shadow-lg">
          <div className="px-5 py-4 border-b border-[#2c2e33] flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-[#39FF14]/10 border border-[#39FF14]/20 flex items-center justify-center">
                <Target className="w-5 h-5 text-[#39FF14]" />
              </div>
              <div>
                <h2 className="text-lg font-bold">Upcoming Match Predictions</h2>
                <p className="text-xs text-[#8b8d93]">Predictions are generated by the configured AI model from football data.</p>
              </div>
            </div>
            <div className="text-xs text-[#8b8d93]">
              {updatedAt ? `Updated ${new Date(updatedAt).toLocaleTimeString()}` : 'Waiting for analysis...'}
            </div>
          </div>

          {loading ? (
            <div className="p-10 flex items-center justify-center gap-3 text-sm text-[#8b8d93]">
              <Loader2 className="w-5 h-5 animate-spin" />
              AI is analyzing upcoming matches...
            </div>
          ) : error ? (
            <div className="p-10 text-center text-sm text-[#8b8d93]">{error}</div>
          ) : predictions.length === 0 ? (
            <div className="p-10 text-center">
              <BrainCircuit className="w-10 h-10 text-[#555] mx-auto mb-3" />
              <p className="text-white font-semibold mb-1">No predictions available</p>
              <p className="text-sm text-[#8b8d93]">There are no suitable upcoming fixtures available for AI analysis right now.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-px bg-[#2c2e33]">
              {predictions.map((prediction) => (
                <article key={prediction.id} className="bg-[#111113] p-6 hover:bg-[#171719] transition-colors">
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 mb-5">
                    <div>
                      <p className="text-[11px] uppercase tracking-wider text-[#8b8d93] mb-1">{prediction.league}</p>
                      <h3 className="text-lg font-bold">{prediction.homeTeam} <span className="text-[#555]">vs</span> {prediction.awayTeam}</h3>
                    </div>
                    <time className="text-xs text-[#8b8d93] whitespace-nowrap">
                      {new Date(prediction.startTime).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                    </time>
                  </div>

                  <div className="grid grid-cols-3 gap-2 mb-5">
                    <div className="rounded-xl border border-[#2c2e33] bg-[#161618] p-3 text-center">
                      <p className="text-[10px] uppercase tracking-wide text-[#8b8d93] mb-1">Home</p>
                      <p className="text-xl font-extrabold">{formatProbability(prediction.homeWin)}</p>
                    </div>
                    <div className="rounded-xl border border-[#2c2e33] bg-[#161618] p-3 text-center">
                      <p className="text-[10px] uppercase tracking-wide text-[#8b8d93] mb-1">Draw</p>
                      <p className="text-xl font-extrabold">{formatProbability(prediction.draw)}</p>
                    </div>
                    <div className="rounded-xl border border-[#2c2e33] bg-[#161618] p-3 text-center">
                      <p className="text-[10px] uppercase tracking-wide text-[#8b8d93] mb-1">Away</p>
                      <p className="text-xl font-extrabold">{formatProbability(prediction.awayWin)}</p>
                    </div>
                  </div>

                  <div className="rounded-xl border border-[#39FF14]/20 bg-[#39FF14]/5 p-4 mb-4">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <p className="text-[10px] uppercase tracking-wider text-[#8b8d93] mb-1">AI prediction</p>
                        <p className="text-xl font-extrabold text-[#39FF14]">{prediction.winner || 'Too close to call'}</p>
                      </div>
                      {prediction.confidence !== null && (
                        <div className="text-right">
                          <p className="text-[10px] uppercase tracking-wider text-[#8b8d93] mb-1">Confidence</p>
                          <p className="text-lg font-extrabold text-white">{prediction.confidence.toFixed(0)}%</p>
                        </div>
                      )}
                    </div>
                    {(prediction.predictedHomeGoals !== null && prediction.predictedAwayGoals !== null) && (
                      <p className="text-xs text-[#b7b9bf] mt-2">
                        Expected score: <span className="text-white font-semibold">{prediction.predictedHomeGoals} - {prediction.predictedAwayGoals}</span>
                      </p>
                    )}
                    {prediction.underOver && <p className="text-xs text-[#b7b9bf] mt-1">Goal outlook: <span className="text-white font-semibold">{prediction.underOver}</span></p>}
                  </div>

                  <div className="rounded-xl border border-[#2c2e33] bg-[#0d0d0f] p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <BrainCircuit className="w-4 h-4 text-[#39FF14]" />
                      <p className="text-xs font-bold uppercase tracking-wide">AI reasoning</p>
                    </div>
                    <p className="text-sm leading-6 text-[#c4c6cb]">
                      {prediction.analysis || prediction.advice || 'The AI did not return a detailed explanation for this fixture.'}
                    </p>
                    {prediction.advice && prediction.analysis && prediction.advice !== prediction.analysis && (
                      <p className="text-xs text-[#8b8d93] mt-3 italic">{prediction.advice}</p>
                    )}
                    {prediction.keyFactors.length > 0 && (
                      <div className="mt-4">
                        <p className="text-[10px] uppercase tracking-wider text-[#6f727a] mb-2">Key factors</p>
                        <ul className="space-y-1.5">
                          {prediction.keyFactors.map((factor, index) => (
                            <li key={`${prediction.id}-factor-${index}`} className="text-xs text-[#b7b9bf] flex gap-2">
                              <span className="text-[#39FF14]">•</span>
                              <span>{factor}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>

                  <div className="mt-4 pt-3 border-t border-[#2c2e33] flex items-center justify-between gap-3 text-[10px] text-[#6f727a]">
                    <span>{formatProvider(prediction.aiProvider)}{prediction.aiModel ? ` · ${prediction.aiModel}` : ''}</span>
                    <span>AI analysis only</span>
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
