import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, History as HistoryIcon, Loader2, RefreshCw, XCircle } from 'lucide-react';
import { getAuthToken } from '../contexts/AuthContext';

interface HistoryItem { id: string; league: string; homeTeam: string; awayTeam: string; startTime: string; winner: string | null; advice: string | null; analysis: string | null; confidence: number | null; predictedHomeGoals: number | null; predictedAwayGoals: number | null; actualHomeScore: number | null; actualAwayScore: number | null; predictionResult: 'true' | 'lose' | 'pending' | null; settledAt: string | null; aiProvider: 'gemini' | 'groq' | null; aiModel: string | null; }
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const authHeaders = () => ({ Authorization: `Bearer ${getAuthToken() || ''}` });
const isoDate = (date: Date) => date.toLocaleDateString('en-CA', { timeZone: 'Africa/Kampala' });
const matchDay = (date: string) => new Intl.DateTimeFormat('en-UG', { timeZone: 'Africa/Kampala', weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(date));
const matchTime = (date: string) => new Intl.DateTimeFormat('en-UG', { timeZone: 'Africa/Kampala', hour: '2-digit', minute: '2-digit' }).format(new Date(date));

export function History() {
  const today = useMemo(() => new Date(), []);
  const initialFrom = useMemo(() => { const d = new Date(today); d.setDate(d.getDate() - 29); return isoDate(d); }, [today]);
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(isoDate(today));
  const [items, setItems] = useState<HistoryItem[]>([]); const [summary, setSummary] = useState({ total: 0, correct: 0, failed: 0, pending: 0, accuracy: 0 }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadHistory = async (manual = false) => { manual ? setRefreshing(true) : setLoading(true); try { if (from > to) throw new Error('The From date cannot be after the To date.'); const response = await fetch(`${API_BASE_URL}/api/football/history?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&ts=${Date.now()}`, { cache: 'no-store', headers: authHeaders() }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || `History returned ${response.status}`); setItems(Array.isArray(payload.items) ? payload.items : []); setSummary(payload.summary || { total: 0, correct: 0, failed: 0, pending: 0, accuracy: 0 }); setError(null); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load prediction history.'); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { loadHistory(); }, []);
  const grouped = useMemo(() => { const groups = new Map<string, HistoryItem[]>(); items.forEach(item => { const key = matchDay(item.startTime); const existing = groups.get(key) || []; existing.push(item); groups.set(key, existing); }); return Array.from(groups.entries()); }, [items]);
  const predictedWinner = (item: HistoryItem) => {
    if (item.winner) return item.winner;
    if (item.predictedHomeGoals !== null && item.predictedAwayGoals !== null) {
      if (item.predictedHomeGoals > item.predictedAwayGoals) return item.homeTeam;
      if (item.predictedAwayGoals > item.predictedHomeGoals) return item.awayTeam;
      return 'Draw';
    }
    return item.advice || 'Prediction unavailable';
  };
  const resultLabel = (item: HistoryItem) => item.predictionResult === 'true' ? 'TRUE' : item.predictionResult === 'lose' ? 'LOSE' : 'PENDING';
  const resultIcon = (item: HistoryItem) => item.predictionResult === 'true' ? <CheckCircle2 className="h-5 w-5 text-[#39FF14]" /> : item.predictionResult === 'lose' ? <XCircle className="h-5 w-5 text-red-400" /> : <Loader2 className="h-5 w-5 animate-spin text-yellow-400" />;
  return <div className="min-h-screen bg-[#0a0a0a] p-6 text-white md:p-10"><div className="mx-auto w-full max-w-7xl">
    <header className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[#39FF14]/20 bg-[#39FF14]/10"><HistoryIcon className="h-6 w-6 text-[#39FF14]" /></div><h1 className="text-3xl font-extrabold tracking-tight md:text-4xl">Prediction History</h1></div><p className="max-w-2xl text-sm text-[#8b8d93] md:text-base">AI predictions are shown immediately. Actual scores and TRUE/LOSE results are filled in after the match is completed and settled. Match days and times are displayed in Africa/Kampala.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-xs text-[#8b8d93]">From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-xl border border-[#2c2e33] bg-[#161618] px-3 py-2 text-sm text-white" /></label><label className="text-xs text-[#8b8d93]">To<input type="date" value={to} min={from} max={isoDate(today)} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-xl border border-[#2c2e33] bg-[#161618] px-3 py-2 text-sm text-white" /></label><button type="button" onClick={()=>loadHistory(true)} disabled={refreshing} className="self-end inline-flex items-center justify-center gap-2 rounded-xl bg-[#39FF14] px-4 py-2.5 text-sm font-bold text-black"><CalendarDays className="h-4 w-4"/>Apply</button></div></header>
    <section className="mb-8 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Analysed games" value={summary.total}/><Stat label="Correct" value={summary.correct} good/><Stat label="Failed" value={summary.failed} bad/><Stat label="Accuracy" value={`${summary.accuracy.toFixed(1)}%`}/></section>
    {loading?<Box>Loading prediction history...</Box>:error?<div className="rounded-2xl border border-red-500/20 bg-[#111113] p-10 text-center"><p className="mb-4 text-red-300">{error}</p><button onClick={()=>loadHistory(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#39FF14] px-4 py-2 text-sm font-bold text-black"><RefreshCw className="h-4 w-4"/>Retry</button></div>:!grouped.length?<Box>No saved predictions in this date range.</Box>:<div className="space-y-8">{grouped.map(([day, dayItems])=><section key={day}><div className="mb-3 flex items-center gap-3"><h2 className="text-lg font-bold">{day}</h2><span className="rounded-full border border-[#2c2e33] bg-[#161618] px-2.5 py-1 text-xs text-[#8b8d93]">{dayItems.length} games</span></div><div className="space-y-3">{dayItems.map(item=><article key={item.id} className="rounded-2xl border border-[#2c2e33] bg-[#111113] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="mb-1 text-[11px] uppercase tracking-wider text-[#6f727a]">{item.league} · {matchTime(item.startTime)}</p><h3 className="text-lg font-bold">{item.homeTeam} <span className="text-[#555]">vs</span> {item.awayTeam}</h3><p className="mt-1 text-sm text-[#8b8d93]">AI prediction: <span className="font-semibold text-white">{predictedWinner(item)}</span>{item.predictedHomeGoals!==null&&item.predictedAwayGoals!==null?` · predicted ${item.predictedHomeGoals}-${item.predictedAwayGoals}`:''}</p></div><div className="flex items-center gap-5"><div className="text-right"><p className="text-[10px] uppercase tracking-wider text-[#6f727a]">Actual</p><p className="text-xl font-extrabold">{item.actualHomeScore!==null&&item.actualAwayScore!==null?`${item.actualHomeScore} - ${item.actualAwayScore}`:'—'}</p></div><div className="flex min-w-[90px] items-center gap-2">{resultIcon(item)}<div><p className="text-[10px] uppercase tracking-wider text-[#6f727a]">Prediction</p><p className={`font-extrabold ${item.predictionResult==='true'?'text-[#39FF14]':item.predictionResult==='lose'?'text-red-300':'text-yellow-300'}`}>{resultLabel(item)}</p></div></div></div></div>{item.analysis&&<p className="mt-4 rounded-xl border border-[#222] bg-[#0d0d0f] p-3 text-sm leading-6 text-[#bfc1c7]">{item.analysis}</p>}<div className="mt-3 flex flex-wrap gap-3 text-[10px] text-[#6f727a]"><span>{item.confidence!==null?`Confidence ${item.confidence.toFixed(0)}%`:'Confidence unavailable'}</span><span>{item.aiProvider?item.aiProvider.toUpperCase():'AI'}</span>{item.aiModel&&<span>{item.aiModel}</span>}</div></article>)}</div></section>)}</div>}
  </div></div>;
}
function Stat({label,value,good,bad}:{label:string;value:string|number;good?:boolean;bad?:boolean}){return <div className={`rounded-2xl border p-4 ${good?'border-[#39FF14]/20 bg-[#39FF14]/5':bad?'border-red-500/20 bg-red-500/5':'border-[#2c2e33] bg-[#111113]'}`}><p className="text-xs text-[#8b8d93]">{label}</p><p className={`mt-1 text-2xl font-extrabold ${good?'text-[#39FF14]':bad?'text-red-300':''}`}>{value}</p></div>}
function Box({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-[#2c2e33] bg-[#111113] p-12 text-center text-sm text-[#8b8d93]">{children}</div>}
