import React, { useEffect, useState } from 'react';
import { TrendingUp, DollarSign, Target, Activity, Loader2 } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
export function Reports() {
  const [stats, setStats] = useState({ total: 0, avg_roi: 0, total_profit: 0 }); const [chartData, setChartData] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API_BASE_URL}/api/reports`).then(r => r.json()).then(data => { if (data.stats) setStats(data.stats); setChartData(data.daily || []); }).catch(error => console.error('Error loading Neon reports:', error)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="h-full flex items-center justify-center"><Loader2 className="w-10 h-10 animate-spin text-indigo-600" /></div>;
  return <div className="p-6 md:p-10 w-full max-w-7xl mx-auto"><h1 className="text-3xl font-extrabold text-slate-900">Reports</h1><p className="text-slate-500 mt-2 mb-8">Performance data calculated directly from Neon PostgreSQL.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8"><div className="bg-white border rounded-2xl p-6"><Activity className="text-indigo-600 mb-4" /><div className="text-3xl font-black">{stats.total}</div><div className="text-sm text-slate-500">Active opportunities</div></div><div className="bg-white border rounded-2xl p-6"><Target className="text-indigo-600 mb-4" /><div className="text-3xl font-black">{Number(stats.avg_roi).toFixed(2)}%</div><div className="text-sm text-slate-500">Average ROI</div></div><div className="bg-white border rounded-2xl p-6"><DollarSign className="text-indigo-600 mb-4" /><div className="text-3xl font-black">{Number(stats.total_profit).toFixed(2)}</div><div className="text-sm text-slate-500">Total tracked profit</div></div></div><div className="bg-white border rounded-2xl p-6"><div className="flex items-center gap-3 mb-6"><TrendingUp className="text-indigo-600" /><h2 className="text-lg font-bold">Last 30 days</h2></div><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Line type="monotone" dataKey="roi" strokeWidth={2} /></LineChart></ResponsiveContainer></div></div></div>;
}
