import React, { useEffect, useState } from 'react';
import { Settings as SettingsIcon, Activity, Target, Loader2, Save, CheckCircle2, Calculator, AlertTriangle, Building2, Info } from 'lucide-react';

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const Toggle = ({ enabled, onChange, label }: { enabled: boolean; onChange: () => void; label?: string }) => <button type="button" onClick={onChange} className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors ${enabled ? 'bg-indigo-600' : 'bg-slate-300'}`} role="switch" aria-checked={enabled} aria-label={label}><span className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow transition ${enabled ? 'translate-x-5' : 'translate-x-0'}`} /></button>;

const estimatedLeaguesPerSport: Record<string, number> = { soccer: 40, basketball: 15, tennis: 20, 'american football': 5, 'ice hockey': 10, 'mixed martial arts': 5, volleyball: 10, baseball: 5 };

export function Settings() {
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saveMessage, setSaveMessage] = useState('');
  const [sports, setSports] = useState<any[]>([]); const [markets, setMarkets] = useState<any[]>([]); const [bookmakers, setBookmakers] = useState<any[]>([]);
  const [globalSettings, setGlobalSettings] = useState({ min_roi: 1, deep_scan: true });

  const fetchData = async () => { try { const response = await fetch(`${API_BASE_URL}/api/settings`); if (!response.ok) throw new Error('Settings request failed'); const data = await response.json(); setSports(data.sports || []); setMarkets(data.markets || []); setBookmakers(data.bookmakers || []); if (data.settings) setGlobalSettings({ min_roi: Number(data.settings.min_roi ?? 1), deep_scan: Boolean(data.settings.deep_scan ?? true) }); } catch (error) { console.error('Error loading scanner settings from Neon API:', error); } finally { setLoading(false); } };
  useEffect(() => { fetchData(); }, []);

  const toggle = async (type: 'sport' | 'market' | 'bookmaker', key: string, active: boolean) => {
    const body = type === 'sport' ? { sportKey: key, active: !active } : type === 'market' ? { marketKey: key, active: !active } : { bookmakerKey: key, active: !active };
    await fetch(`${API_BASE_URL}/api/settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await fetchData();
  };
  const handleSaveGlobals = async () => { setSaving(true); try { await fetch(`${API_BASE_URL}/api/settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(globalSettings) }); setSaveMessage('Preferences saved successfully.'); setTimeout(() => setSaveMessage(''), 4000); } finally { setSaving(false); } };

  const activeSportsKeys = sports.filter(s => s.active).map(s => s.key); const estimatedLeaguesCount = activeSportsKeys.reduce((total, key) => total + (estimatedLeaguesPerSport[key] || 5), 0); const estimatedRequestsPerCycle = 1 + estimatedLeaguesCount; const isOverLimit = estimatedRequestsPerCycle > 100;
  if (loading) return <div className="h-full w-full flex items-center justify-center"><Loader2 className="w-10 h-10 text-indigo-600 animate-spin" /></div>;

  return <div className="p-6 md:p-10 w-full max-w-7xl mx-auto pb-24">
    <div className="flex items-center gap-4 mb-2"><div className="w-12 h-12 rounded-xl bg-indigo-50 flex items-center justify-center border border-indigo-100 shadow-sm"><SettingsIcon className="w-6 h-6 text-indigo-600" /></div><h1 className="text-3xl font-extrabold text-slate-900">Scanner Settings</h1></div>
    <p className="text-slate-500 text-sm font-medium mb-10 ml-16">Configure the Neon-backed scanner: sports, markets, bookmakers and minimum ROI.</p>
    <div className="mb-8 bg-emerald-50 border border-emerald-200 rounded-2xl p-5 flex items-start gap-3"><CheckCircle2 className="w-6 h-6 text-emerald-600" /><div><p className="font-bold text-emerald-900">Automatic scanning is always enabled.</p><p className="text-sm text-emerald-800 mt-1">New matches are generated every 12 hours. Live matches are refreshed every 2 minutes by the backend.</p></div></div>
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-8"><div className="xl:col-span-2 space-y-8">
      <div className="bg-white border border-slate-200 shadow-sm rounded-2xl overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><Building2 className="w-5 h-5 text-indigo-600" /><div><h2 className="text-lg font-bold text-slate-900">Bookmakers</h2><p className="text-sm text-slate-500">At least two active bookmakers are required.</p></div></div><div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-4">{bookmakers.map(b => <div key={b.key} className="flex items-center justify-between p-4 rounded-xl border border-slate-200"><span className="text-sm font-bold text-slate-900">{b.title}</span><Toggle enabled={b.active} onChange={() => toggle('bookmaker', b.key, b.active)} /></div>)}</div></div>
      <div className="bg-white border border-slate-200 shadow-sm rounded-2xl overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><Activity className="w-5 h-5 text-indigo-600" /><div><h2 className="text-lg font-bold text-slate-900">Sports</h2><p className="text-sm text-slate-500">Active sports are discovered automatically each 12-hour cycle.</p></div></div><div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-4">{sports.map(s => <div key={s.key} className="flex items-center justify-between p-4 rounded-xl border border-slate-200"><span className="text-sm font-bold text-slate-900">{s.title}</span><Toggle enabled={s.active} onChange={() => toggle('sport', s.key, s.active)} /></div>)}</div></div>
      <div className="bg-white border border-slate-200 shadow-sm rounded-2xl overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><Target className="w-5 h-5 text-indigo-600" /><div><h2 className="text-lg font-bold text-slate-900">Markets</h2><p className="text-sm text-slate-500">Markets compared by the arbitrage engine.</p></div></div><div className="p-6 space-y-4">{markets.map(m => <div key={m.key} className="flex items-center justify-between p-4 rounded-xl border border-slate-200"><div><div className="text-sm font-bold text-slate-900">{m.title}</div><div className="text-xs text-slate-500">{m.description}</div></div><Toggle enabled={m.active} onChange={() => toggle('market', m.key, m.active)} /></div>)}</div></div>
    </div><div className="space-y-8">
      <div className={`border shadow-sm rounded-2xl overflow-hidden ${isOverLimit ? 'bg-red-50 border-red-200' : 'bg-white border-slate-200'}`}><div className="p-6 border-b flex items-center gap-3"><Calculator className="w-5 h-5 text-indigo-600" /><div><h2 className="text-lg font-bold text-slate-900">API Usage Estimate</h2><p className="text-sm text-slate-500">Estimated requests per 12-hour cycle.</p></div></div><div className="p-6"><div className="flex justify-between items-end mb-5"><div><div className="text-5xl font-black">~{estimatedRequestsPerCycle}</div><div className="text-sm font-bold uppercase tracking-wider mt-1 text-slate-400">requests / cycle</div></div><div className="text-right"><div className="text-base font-extrabold text-slate-700">~{estimatedLeaguesCount} leagues</div><div className="text-sm text-slate-500">one cycle every 12 hours</div></div></div>{isOverLimit && <div className="flex gap-3 text-sm text-red-800 bg-red-100 p-4 rounded-xl border border-red-200"><AlertTriangle className="w-5 h-5" /><p>This configuration may exceed a 100-request hourly limit.</p></div>}</div></div>
      <div className="bg-white border border-slate-200 shadow-sm rounded-2xl overflow-hidden sticky top-8"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><SettingsIcon className="w-5 h-5 text-indigo-600" /><div><h2 className="text-lg font-bold text-slate-900">Scanner Rules</h2><p className="text-sm text-slate-500">Stored in Neon PostgreSQL.</p></div></div><div className="p-6 space-y-6"><div><label className="block text-sm font-bold text-slate-700 mb-2">Minimum ROI</label><div className="relative"><input type="number" step="0.1" min="0" value={globalSettings.min_roi} onChange={e => setGlobalSettings({ ...globalSettings, min_roi: Number(e.target.value) })} className="w-full bg-white border border-slate-300 rounded-xl px-4 py-3 text-slate-900 font-bold" /><span className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">%</span></div></div><div className="flex items-center justify-between"><div><div className="text-sm font-bold text-slate-700">Deep scan</div><div className="text-xs text-slate-500">Use the configured deeper analysis mode.</div></div><Toggle enabled={globalSettings.deep_scan} onChange={() => setGlobalSettings({ ...globalSettings, deep_scan: !globalSettings.deep_scan })} /></div><button onClick={handleSaveGlobals} disabled={saving} className="w-full flex items-center justify-center gap-2 rounded-xl bg-indigo-600 text-white py-3 font-bold disabled:opacity-50">{saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />} Save preferences</button>{saveMessage && <p className="text-sm font-bold text-emerald-600 flex items-center gap-2"><Info className="w-4 h-4" />{saveMessage}</p>}</div></div>
    </div></div>
  </div>;
}
