const { Pool } = require('pg');
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false } }) : null;
const memory = new Map();
async function init(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS predictions(id TEXT PRIMARY KEY,fixture_date TIMESTAMPTZ NOT NULL,home_team TEXT NOT NULL,away_team TEXT NOT NULL,league TEXT,fixture_status TEXT,generated_at TIMESTAMPTZ NOT NULL,prediction JSONB NOT NULL,result_status TEXT NOT NULL DEFAULT 'PENDING',actual_home_goals INTEGER,actual_away_goals INTEGER,actual_result TEXT,settled_at TIMESTAMPTZ)`);await pool.query(`CREATE TABLE IF NOT EXISTS automation_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled BOOLEAN NOT NULL DEFAULT FALSE,run_hour INTEGER NOT NULL DEFAULT 6,run_minute INTEGER NOT NULL DEFAULT 0,timezone TEXT NOT NULL DEFAULT 'Africa/Kampala',last_run_date DATE,last_run_at TIMESTAMPTZ,last_run_status TEXT,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`INSERT INTO automation_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING`);}
async function savePredictions(items){for(const x of items){const p=x.ai||{},rs=p.failed?'FAILED':'PENDING';if(!pool){memory.set(x.id,{...x,resultStatus:rs});continue;}await pool.query(`INSERT INTO predictions(id,fixture_date,home_team,away_team,league,fixture_status,generated_at,prediction,result_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET fixture_status=EXCLUDED.fixture_status`,[x.id,x.utcDate,x.homeTeam,x.awayTeam,x.league,x.status,x.generatedAt||new Date().toISOString(),JSON.stringify(p),rs]);}}
function map(r){return{id:r.id,utcDate:r.fixture_date,homeTeam:r.home_team,awayTeam:r.away_team,league:r.league,status:r.fixture_status,generatedAt:r.generated_at,ai:r.prediction,resultStatus:r.result_status,actualHomeGoals:r.actual_home_goals,actualAwayGoals:r.actual_away_goals,actualResult:r.actual_result,settledAt:r.settled_at};}
async function listPredictions({history=true,limit=1000}={}){if(!pool)return[...memory.values()].slice(-limit).reverse().filter(x=>history||x.resultStatus==='PENDING');const q=history?'SELECT * FROM predictions ORDER BY fixture_date DESC LIMIT $1':`SELECT * FROM predictions WHERE result_status='PENDING' ORDER BY fixture_date ASC LIMIT $1`;return(await pool.query(q,[limit])).rows.map(map);}
async function settlePrediction(id,hg,ag,status='FINISHED'){const result=hg>ag?'HOME':hg<ag?'AWAY':'DRAW';if(!pool){const x=memory.get(id);if(!x||x.resultStatus!=='PENDING'||x.ai?.failed)return false;memory.set(id,{...x,status,resultStatus:x.ai.verdict===result?'WIN':'LOSE',actualHomeGoals:hg,actualAwayGoals:ag,actualResult:result,settledAt:new Date().toISOString()});return true;}const r=await pool.query('SELECT prediction,result_status FROM predictions WHERE id=$1',[id]);if(!r.rowCount||r.rows[0].result_status!=='PENDING'||r.rows[0].prediction?.failed)return false;const outcome=r.rows[0].prediction?.verdict===result?'WIN':'LOSE';await pool.query(`UPDATE predictions SET fixture_status=$2,actual_home_goals=$3,actual_away_goals=$4,actual_result=$5,result_status=$6,settled_at=NOW() WHERE id=$1 AND result_status='PENDING'`,[id,status,hg,ag,result,outcome]);return true;}
async function getAutomation(){if(!pool)return{enabled:false,runHour:6,runMinute:0,timezone:'Africa/Kampala',lastRunDate:null,lastRunAt:null,lastRunStatus:'DATABASE_REQUIRED'};const x=(await pool.query('SELECT * FROM automation_settings WHERE id=1')).rows[0];return{enabled:x.enabled,runHour:x.run_hour,runMinute:x.run_minute,timezone:x.timezone,lastRunDate:x.last_run_date,lastRunAt:x.last_run_at,lastRunStatus:x.last_run_status};}
async function setAutomation({enabled,runHour,runMinute,timezone}){if(!pool)throw new Error('DATABASE_URL is required for persistent automation.');await pool.query(`UPDATE automation_settings SET enabled=$1,run_hour=$2,run_minute=$3,timezone=$4,updated_at=NOW() WHERE id=1`,[!!enabled,Number(runHour),Number(runMinute),timezone||'Africa/Kampala']);return getAutomation();}
async function markRun(date,status){if(pool)await pool.query(`UPDATE automation_settings SET last_run_date=$1,last_run_at=NOW(),last_run_status=$2 WHERE id=1`,[date,status]);}
async function getPerformance(){if(!pool){const a=[...memory.values()],s=a.filter(x=>['WIN','LOSE'].includes(x.resultStatus)),w=s.filter(x=>x.resultStatus==='WIN').length;return{total:a.length,settled:s.length,wins:w,losses:s.length-w,pending:a.filter(x=>x.resultStatus==='PENDING').length,failed:a.filter(x=>x.resultStatus==='FAILED').length,accuracy:s.length?Number((w/s.length*100).toFixed(2)):null};}const x=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE result_status IN('WIN','LOSE'))::int settled,COUNT(*) FILTER(WHERE result_status='WIN')::int wins,COUNT(*) FILTER(WHERE result_status='LOSE')::int losses,COUNT(*) FILTER(WHERE result_status='PENDING')::int pending,COUNT(*) FILTER(WHERE result_status='FAILED')::int failed FROM predictions`)).rows[0];return{...x,accuracy:x.settled?Number((x.wins/x.settled*100).toFixed(2)):null};}
module.exports={pool,init,savePredictions,listPredictions,settlePrediction,getAutomation,setAutomation,markRun,getPerformance};